name: ECS CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - uses: extractions/setup-just@v2

      - name: build ECS
        uses: leanprover/lean-action@v1

      # inherits lake installation from the previous step
      - name: build example
        working-directory: examples
        run: just build
